### ISSUE TITLE
GUI Development

### ISSUE THREAD

**Issue by CarlosDavey** [CarlosDavey/thesis-JUCE-repo#5]
So even though the final design is still very much in development there are a few features I am keen to implement, and am wondering if it might be sensible to start on those in a modular fashion so they can just be brought in later once the positions/sizes ect art decided?

1. Basic Graphic EQ with two moveable nodes, i.e. ![image](https://user-images.githubusercontent.com/52743332/120616991-9bc97b80-c451-11eb-823f-9df09e9490a9.png)
2. A "waves style" utility bar with help button, preset controls etc along the top ![image](https://user-images.githubusercontent.com/52743332/120617201-cadfed00-c451-11eb-806b-4799608845a6.png)
3. Some kind of visualisation that adapts to user controls. Obvious choice is the IR, so you can see the damping stretch it out etc but not sure how this could be done outside of just loading controls... 

The rest will be some combination of sliders/dials etc TBC but the parameters I want to control are: 

- Decay Time 
- Pre-Delay
- Wet/Dry (Individual gain sliders NOT a crossfader)
- Physical Parameter 1 (i.e spring density, radius, tbc)
- Physical Parameter 2 

What do you think? Is it a good idea to get started before the final design is settled on or is that a no-go?

**Comment by mhamilt** [comment]
We can just decompose each component then all you need to do is build them up.

### 1. Basic Graphic EQ with two moveable nodes

- [ ]A [JUCE Path](https://docs.juce.com/master/classPath.html) with simple lines for bottom, left, right
- [ ] series of splines connecting specific bands to the top
- [ ] A fill colour
- [ ] (optional) a marker for each for each. frequency band (a rectangle, a circle)
- [ ] A rectangle for the bounds of the graph
- [ ] a centre line to help mark ± gain
- [ ] tick labels for Frequency
- [ ] test for mouse postion
- [ ] listen for mouse click
- [ ] if mouse

**Comment by mhamilt** [comment]
### 2. utility bar 

- [ ] [Possibly MenuBarComponent](https://docs.juce.com/master/classMenuBarComponent.html#abf1f80e5c336530b69eee23f84a56a38)
- [ ] or a series of [Buttons](https://docs.juce.com/master/structButton_1_1LookAndFeelMethods.html) and [Popup Menu](https://docs.juce.com/master/structPopupMenu_1_1LookAndFeelMethods.html)


### 3. visualisation

For a waveform

- [ ] get peaks from frames of IR
- [ ] for each peak draw a centred rectangle or a path mirrored on a centre line

**Comment by mhamilt** [comment]
> What do you think? Is it a good idea to get started before the final design is settled

You can certainly start, but be aware you might need to trash your work if you decide to do something different.

**Comment by CarlosDavey** [comment]
Okay thanks! Do you know of a particularly good tutorial etc for learning how to get started with this sort of thing in JUCE/C++?

**Comment by mhamilt** [comment]
There are a couple of aspects to this. For GUIs in JUCE there is the actual drawing, listeners, the GUI classes, Look&Feel inheritance.

The GUI calls for at least one custom object, the Graphic Equaliser. The main task for that is the drawing. If you aren't used to drawing with code, I'd actually recommend photo-typing some ideas in [Processing](https://processing.org) rather than C++ / JUCE. You'll eschew some of the noise / compile time and be able to focus on learning the principles of procedural drawing.

You already have a solid grounding in programming principles, so the rest is just getting used to how to organise yourself.

Tutorial-wise, [Learning Processing](http://learningprocessing.com/examples/) would be helpful to skim through.
